### ISSUE TITLE
What brand?

### ISSUE THREAD

**Issue by lizzieinvancouver** [temporalecologylab/labshirts#1]
are our current shirts?

**Comment by cchambe12** [comment]
[Alternative! ](https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=2ahUKEwj1noyA38TeAhWkdN8KHajtATUQjRx6BAgBEAU&url=https%3A%2F%2Fwww.alternativeapparel.com%2Fnew-york-reverse-crew-t-shirt-i4115ij&psig=AOvVaw11BXHZnyxTTFXJCF5COBuE&ust=1541764637974609)
